language: rust
rust:
 - nightly

install:
 - nvm install node
 - cargo install wasm-bindgen-cli
 - rustup target add wasm32-unknown-unknown
 - npm install
 - npm install webpack-cli

script:
 - mkdir dist
 - cargo build --release --target wasm32-unknown-unknown
 - wasm-bindgen --browser --no-typescript ./target/wasm32-unknown-unknown/release/vector_track.wasm --out-dir .
 - npm run webpack-cli
 - cp index.html dist/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
