language: rust
rust:
 - nightly

cache:
 - ~/.cargo

install:
 - nvm install node
 - cargo install wasm-bindgen-cli
 - rustup target add wasm32-unknown-unknown
 - npm install webpack-cli@3.1.1 webpack@4.20.2

script:
 - mkdir dist
 - cargo build --release --target wasm32-unknown-unknown
 - wasm-bindgen --browser --no-typescript ./target/wasm32-unknown-unknown/release/vector_track.wasm --out-dir .
 - ./node_modules/.bin/webpack --config ./webpack.config.js
 - cp index.html dist/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
