[package]
name = "vector_track"
version = "0.1.0"
authors = ["Mark Simulacrum <mark.simulacrum@gmail.com>"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["spans", "std"] }

[profile.release]
debug = true
lto = true
